### ISSUE TITLE
Compiling on Ubuntu 17.04

### ISSUE THREAD

**Issue by jwmatthys** [RTcmix/RTcmix#12] opened 2017-05-24 05:16 UTC
Trying to build the MAXMSP version on Linux (g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0) so I work on updating rtcmix~ on Pd) and I get a couple of errors:

`make[3]: Entering directory '/home/jwmatthys/Audio/RTcmix/insts/std/LPCPLAY'
g++ -Wno-deprecated  -I. -I/home/jwmatthys/Audio/RTcmix/include  -O2 -Wall -Wno-unused -fPIC -DLINUX -m64  -DSTANDALONE  -I. -DUSE_HEADERS   -c -o stabilize.o stabilize.cpp
stabilize.cpp: In function ‘double abs(double)’:
stabilize.cpp:31:27: error: ‘double abs(double)’ conflicts with a previous declaration
 inline double abs(double x) { return (x >= 0.) ? x : -x; }
                           ^
In file included from /usr/include/c++/6/math.h:36:0,`

This one is easily fixed by commenting out line 37 of stabilitze.cpp. I don't know if other compilers aren't pulling in stdlib or are missing abs (seems unlikely). Maybe an IFDEF is needed? I know LPCPLAY is an old instrument; maybe this line of code can safely be removed.

The other issue I get is:
`In file included from minc.y:12:0:
lex.yy.c: In function ‘int mm_yy_get_next_buffer()’:
minc.l:41:80: error: cannot convert ‘int*’ to ‘yy_size_t* {aka long unsigned int*}’ for argument ‘2’ to ‘int readFromGlobalBuffer(char*, yy_size_t*, int)’
 #define YY_INPUT(buf,bytes,maxbytes) readFromGlobalBuffer(buf,&(bytes),maxbytes)
`

I'm afraid that flex stuff is a black box to me. Any suggestions on fixing this? Thanks!

**Comment by dougscott** [comment] 2017-05-24 14:55
To the best of my knowledge, RTcmix has never been used to build MAX for
Linux.  I suspect it has multiple OS X dependencies.  However, the first
error you show above does not seem related to MAX (I built stabilize.cpp
for Linux just the other day) so must be a compiler version issue.

You'll need to just post these (you can do this via GitHub if you want, or
here is fine) and I will fix them as I see them.

-Doug

**Comment by dougscott** [comment] 2017-05-25 14:15
Joel, can type 'make print-CFLAGS' at the top of your Linux RTcmix source
where you are trying to build for MAX?  I need to see your arguments,
because it looks to me like building for Linux right now is forcing
-DSTANDALONE, which will not work.

By the way, I checked in the fix for the first compile problem, but I need
to reproduce the second one to figure out how to fix it.

-Doug

**Comment by dougscott** [comment] 2017-05-25 14:24
Also, it appears that there is a hidden BUILDTYPE for "PD" - would this
likely be what you as a Linux builder would set, rather than MAXMSP?  It
won't work right now.

How long ago was the last RTcmix that was built for PD?  I need to
understand things like which AudioDevice class you used to connect RTcmix
to PD.

I'm glad that someone was finally the guinea pig for getting all the Linux
config stuff ironed out -- all I've heard is Mac Mac Mac for the longest
time...   ;)

-Doug

**Comment by dougscott** [comment] 2017-05-25 14:26
One more!  Should people expect to be able to build a Pd configuration of
RTcmix for both Linux and OSX?

-Doug

**Comment by dougscott** [comment] 2017-05-25 14:54
OK, checked in a fix for the Linux-embedded-config error in
src/parser/minc.  Let's see what's next!

-Doug

**Comment by jwmatthys** [comment] 2017-05-26 05:57
Hi Doug. I have been seeing your messages both on the rtcmix-discuss 
list and the GitHub notification system.

I would like to use the PD buildtype on both Linux and OSX (and maybe 
even Windows, eventually) but I thought it would be best to just start 
with any working method to get a library I can link to.

Myprevious version was based on Brad's rtcmix~ v. 1.92 I think. It used 
the pullTraverse() method. I agree with you and Brad that the 
OSXEMBEDDED build type is probably the best starting point. I'll add in 
the Pd-specific glue once I get all of the RTcmix stuff compiling 
successfully.

I grabbed the latest changes from GitHub and set site.conf to MAXMSP. 
The only errors I get now are from the missing Max SDK, so that's good. 
And I can build and run the standalone (once I add the AUDIODEVICE = 
ALSA in site.conf).

When I specify MAXMSP in site.conf, I still get this from make print-CFLAGS:

CFLAGS is -I. -I/home/jwmatthys/Audio/RTcmix/include -O2 -Wall 
-Wno-unused -fPIC -DLINUX -m64 -DSTANDALONE

It looks like makefile.conf.in doesn't check build type yet in the Linux 
arch section. That's an easy fix I'll be glad to work on.

Joel

**Comment by dougscott** [comment] 2017-05-26 14:44
Please let me make the config changes for this.  I have the work mostly
done already.

I was going to ask you if you could get me the source for your Pd
equivalent of the rtcmix~.c file -- I assume it is not identical to Brad's
original because I can't imagine Pd has the same internal structure.

Didn't you get a linker error in src/rtcmix/message.o for the "cpost"
function?  The Linux linker flags don't know to suppress the warning about
that symbol being undefined.

Can you tell me the ways you would expect BUILDTYPE=PD to be different than
BUILDTYPE=MAXMSP?

Right now, in the RTcmix source, there is a single place where a function
has a different name when building for PD vs. MAXMSP -- that's it.

Once I have your Pd version of rtcmix~.c to modify and the information
above, I can move pretty quickly on getting this set up for you.

-Doug

**Comment by jwmatthys** [comment] 2017-05-26 15:41
The source for rtcmix~.c and .h are here: https://github.com/jwmatthys/rtcmix-in-pd. At that time, I used the same approach Brad used, loading RTcmix as a dylib.

For a new version, I want to build a single fat external without external linking. I also need to rewrite the text editor to use the new methods introduced in recent Pd versions.

**Comment by dougscott** [comment] 2017-05-26 16:30
If I understand you, you want to link RTcmix against your PD binary as a
static lib (libRTcmix.a)?

I'll look at your repository today.  Does Pd have a "cpost" function which
prints messages to some sort of internal logging system (like Max)?

-Doug

**Comment by jwmatthys** [comment] 2017-05-27 02:08
Correct, I'd like a static librtcmix.a.

Pd has "post" which is IIRC equivalent to Max's cpost. The only modifications I made to the RTcmix source for my old rtcmix~ was to add post messages.

**Closed** 2017-06-30 07:04 UTC
